import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  BrowserRouter as Router,
  Route,
  Routes,
  Navigate,
} from "react-router-dom";
import SecuredPagesLayout from "@/components/layout/SecuredPagesLayout";
import UnsecuredPagesLayout from "@/components/layout/UnsecuredPagesLayout";
import Dashboard from "./(secured)/Dashobard";
import TransportTicketsPage from "./(secured)/Tickets/Transport";
import SiginPage from "./(unsecured)/(auth)/Signin";
import SignUpPage from "./(auth)/signup/page";
import { useEffect } from "react";
import { RouteWithMeta } from "@/components/layout/MainLayout/utils/RouteWithMeta";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface RouteConfig {
  path: string;
  element: React.ReactElement;
  meta?: {
    title?: string;
    description?: string;
  };
}
const protectedRoutes: RouteConfig[] = [
  {
    path: "/dashboard",
    element: <Dashboard />,
    meta: { title: "Dashboard", description: "User Dashboard" },
  },
  {
    path: "/tickets/transport",
    element: <TransportTicketsPage />,
    meta: { title: "Transport Tickets", description: "User Transport Tickets" },
  },
];

const unprotectedRoutes: RouteConfig[] = [
  {
    path: "/sign-in",
    element: <SiginPage />,
    meta: { title: "Login", description: "Login Page" },
  },
  {
    path: "/sign-up",
    element: <SignUpPage />,
    meta: { title: "Signup", description: "Signup Page" },
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>

      <Router>
      <nav>
        <ul>
          {protectedRoutes.map(route => (
            <li key={route.path}>
              <a href={route.path}>{route.meta?.title}</a>
            </li>
          ))}
          {unprotectedRoutes.map(route => (
            <li key={route.path}>
              <a href={route.path}>{route.meta?.title}</a>
            </li>
          ))}
        </ul>
      </nav>
      <Routes>
        {protectedRoutes.map(route => (
          <Route
            path={route.path}
            key={route.path}
            element={
              <SecuredPagesLayout>
                <RouteWithMeta route={route} />
              </SecuredPagesLayout>
            }
          />
        ))}
        {unprotectedRoutes.map(route => (
          <Route
            path={route.path}
            key={route.path}
            element={
              <UnsecuredPagesLayout>
                <RouteWithMeta route={route} />
              </UnsecuredPagesLayout>
            }
          />
        ))}
        <Route path="*" element={<Navigate to="/login" />} />
      </Routes>
    </Router>
    </html>
  );
}
